version: 2.1
orbs:
  node: circleci/node@5.2.0
jobs:
  build:
    executor:
      name: node/default
      tag: '22.x'
    steps:
      - checkout
      - run:
          name: install & lint & export
          command: npm ci && npm run export
